### PR TITLE
again desgin the software

### PR DESCRIPTION
**Pull request by Mandeep28**
In this pull request I do some changes .
1. redesign the navbar add the round user button for logout and setting  for the admin . 
2. change the edit and delete functionality for the guide edit and delete button but the problem that I face is when I  add new guide the success message is not showing in the add vala page instead it show the message in the edit valla page. ( please fix it)
3. add the data tables inside the session page but It can't take the css file and give error ( please filx it ) as I create a new css file name as "header&footer.css" 
4. also I can't do the validation for edit and add guide and this is done very soon...

### CODE REVIEW

**Comment by GurpreetSarangal** [comment]
Hi @Mandeep28, I've checked your changes. Everything is working good. Datatables are really impressive, the search also great. 
But I came across some issues like 
- [x] while deleting the guide, it always deletes the first guide. 
- [ ] navbar in class-template page should have a smaller font size.
- [x] edit-guide page's form isn't centred (I can fix it btw).
- [ ] logout and settings button messes up with datatable, please fix that.

**Comment by GurpreetSarangal** [comment]
I'll check the messages problem.  
and the sessions page is now working good. All css files are getting loaded.

**Comment by GurpreetSarangal** [comment]
And what did you meant by the 4<sup>th</sup> point. I didn't get it 😅

**Comment by Mandeep28** [comment]
4 point means that client side validation is not done yet but it will be done very soon....

**Pull request merged**
